---
- name: Example for using variables
  hosts: test
  become: true
  vars:
    name: john_doe  
  tasks:
    - name: Create user
      user:
        name: "{{ name }}"
        state: present  
  

- name: Install and configure Apache
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
      when: ansible_facts['distribution'] in ['CentOS', 'RedHat']  # Use a broader check for CentOS and RHEL family systems  
      notify:
        - Restart Apache  # Notify the handler to restart Apache if the package is installed

    - name: Copy custom Apache config
      copy:
        src: /path/to/apache/config.conf
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - Restart Apache  # Notify the handler to restart Apache if the config is changed

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted  # Restart the Apache service          
