---
- name: Update web servers
  hosts: webservers
  become: true

  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Ensure Apache is started and enabled on boot
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes


- name: Install and start PostgreSQL on db servers
  hosts: database
  become: true

  tasks:
    - name: Ensure postgresql is at the latest version
      ansible.builtin.apt:
        name: postgresql
        state: latest
        update_cache: yes

    - name: Ensure that postgresql is started
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes
